{
 "title": "Monitoramento de Requests - CaioPedroso",
 "tags": [ "Banco de Dados" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status do Node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up", "legendFormat": "Node {{instance}}" }
   ]
  },
  {
   "title": "Requests em Processo",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight",
     "legendFormat": "Nº de Requests"
    }
   ]
  },
  {
   "title": "% de CPU Utilizada (Prometheus)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "Uso de CPU"
    }
   ]
  },
  {
   "title": "Uso de Memória (Prometheus)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[1m])",
     "legendFormat": "Uso de Memória"
    }
   ]
  },
  {
   "title": "Tempo Médio de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[1m]) / rate(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "Segundos"
    }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[1m])",
     "legendFormat": "Requisições/s"
    }
   ]
  },
  {
   "title": "Taxa de Erros (HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total{status!~'2..'}[1m])",
     "legendFormat": "Erros/s"
    }
   ]
  }
 ]
}