FROM grafana/grafana:latest

# Copia os arquivos de configuração
COPY provisioning/datasources/ /etc/grafana/provisioning/datasources/
COPY provisioning/dashboards/ /etc/grafana/provisioning/dashboards/
COPY dashboards/ /var/lib/grafana/dashboards/


# Permissões para o grafana
USER root
RUN chmod -R 755 /etc/grafana /var/lib/grafana
USER grafana